### ISSUE TITLE
Solid Panelist - Description

### ISSUE THREAD

**Issue by eduardoinnorway** [solid/community#11]
I am missing a description on community-roles.md that describes "Solid Panelist"

**Comment by Mitzi-Laszlo** [comment]
How about.. 

**Panel Coordinator** 
Panel Coordinators are responsible for designing and running tests with the Solid Panelists as well as publishing test results to the Solid community. Panel Coordinators are expected to join the weekly User Testing meeting which is moderated by the Community Manager. 

* **Solid Panelist** 
Solid Panelists are individuals who are available for a range of tests over time to improve the Solid user experience. When there is a test set up by the Panel Coordinators, the Community Manager will reach out to the relevant Solid Panelists to ask if they would like to participate in that particular test. Each test will take approximately 30 minutes, Solid Panelists are not obliged to participate in all tests, and Solid Panelists can stop being on the Solid Panel at any point. Tests will be designed to improve the Solid experience.

**Comment by Mitzi-Laszlo** [comment]
@eduardoinnorway are you satisfied with this conclusion?
