### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by wrmack** [solid/community#17]
https://github.com/solid/community
Under Solid Related Tools.

Links to Pod Providers, WebID Provider,  Developer Support Tools are broken.

**Comment by Mitzi-Laszlo** [comment]
Well spotted, the new links have been added and pull requests submitted for content.

**Comment by Mitzi-Laszlo** [comment]
Once the relevant pull requests have been reviewed, I can make sure these links are updated.

**Comment by Mitzi-Laszlo** [comment]
@wrmack are you satisfied with this conclusion?

**Comment by fils** [comment]
FYI..   there still seem to be lots of broken links in the README.md in the Provider section.
