### ISSUE TITLE
contacting `Core Developer` or `Community Manager`

### ISSUE THREAD

**Issue by ericprud** [solid/community#3]
The [Code of Conduct](https://github.com/solid/community/blob/master/code-of-conduct.md) suggests that people contact `Core Developer` or `Community Manager`s without saying how to do so.

**Comment by Mitzi-Laszlo** [comment]
Now that the [roles are formally allocated and stated](https://github.com/solid/community/blob/master/community-roles.md) perhaps who to contact is clearer. One option would be to link the word "contact the community manager" to the community repo readme where the individuals in the roles are. How would you alter which text in a way that you feel would be easy to find and clear?

**Comment by Mitzi-Laszlo** [comment]
@ericprud are you satisfied with this conclusion?
