### ISSUE TITLE
Questions for Solid World February 2019

### ISSUE THREAD

**Issue by Mitzi-Laszlo** [solid/community#34]
The theme for [Solid World](https://www.eventbrite.com/e/solid-world-tickets-53692744444) February 2019 with be Solid Chat and the Solid App presentation will be by @pheyvaer. Let me know if you have any questions in advance by replying to this issue or writing me a personal message on gitter.

**Comment by ghsnd** [comment]
Hi, I attended the event yesterday and I found it to be really interesting and well done. However, what I missed a bit was some _action_. For instance, a very short demo of the app that is being presented, or code snippets that show how the app uses Solid, ... Things that make developers want to try it out. Maybe something for next time?
