### ISSUE TITLE
New User Creation

### ISSUE THREAD

**Issue by Gralen84** [solid/community#4]
When creating a UserID, it's not clear to the layman that they have to keep it all lowercase.  When generating the "invalid username" error, it might be helpful to include any requirements/restrictions.  There's a lot of people hearing about this and if they can't figure out how to create a POD easily, they won't as it will be "too difficult".

**Comment by kjetilk** [comment]
Yeah, I can see that. We have a prioritized issue open on this: https://github.com/solid/solid/issues/205 we'll follow up there.
