### ISSUE TITLE
Add point about being mindful of people's time and effort

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/community#5]
It has occurred a couple of times recently and in the past that people are engaging in long conversations, but are not adequately reacting to other people's points.

I would like to add a point about how we should respect people's time and effort, regardless of whether they are volunteers or not. Concretely, this involves listening to what people write, and replying to their points as appropriate. Essentially, following proper argument structure as a sign of respect for each other's time and effort.

**Comment by Mitzi-Laszlo** [comment]
As a way forward, @RubenVerborgh shall we add a point to the code of conduct?

**Comment by RubenVerborgh** [comment]
I had a suggestion in #6. I still think it's important, but we might need broader support for changes like this.

**Comment by Mitzi-Laszlo** [comment]
Yes, understood. 

Perhaps this is way out and too corny but we could you a flag of compassion http://www.flagofcompassion.com/EN/index.html image or label on comments that are not taking into account the broader conversation and invite the commenter to take a second read. 

thoughts? any alternative solutions?
