### ISSUE TITLE
What are the logo usage guidelines?

### ISSUE THREAD

**Issue by Otto-AA** [solid/community#68]
In the readme [is stated](https://github.com/solid/community#solid-logo), that "There are defined Solid logo usage guidelines", yet [the linked](https://github.com/solid/community/blob/master/solid-logo-usage-guidelines.md) file is empty for me. Are there any official guidelines for its use?

**Comment by Mitzi-Laszlo** [comment]
Hi Otto-A-A, 

There are no guidelines as of yet, would you like to develop some? 

Mitzi
