### ISSUE TITLE
Add labels to signal whether commenter's issue is fulfilled

### ISSUE THREAD

**Issue by csarven** [solid/community#7]
Adopt labels to some of the GitHub repositories along the following lines:

* Commenter Not Satisfied
* Commenter Satisfied
* Commenter Timeout (assuming satisfied)

It is courteous to the original commenter that their issues were sufficiently addressed or consensus was reached. Perhaps most importantly for the well-being of the community, they were involved in the decision process.

It is definitely not bullet-proof, but it potentially encourages positive involvement for all parties. [FWIW, we used this in the W3C SocialWeb WG, and I think it worked out ok.]

In some cases, asking the original commenter at the end of a reply whether the issue was sufficiently addressed, and if so, they can close the issue themselves.

**Comment by Mitzi-Laszlo** [comment]
What would "Commenter Timeout" mean?

**Comment by csarven** [comment]
@megoth That's right. To take an example, if there was a proposal in this issue in response to the original inquiry, and say I didn't respond for 'some time' (whatever the urgency and need - depends on the judgement of those involved), then whoever is keeping an eye on the repo or issues can mark it as 'commenter timeout' and carry on with the proposal, close the issue etc.

**Comment by Mitzi-Laszlo** [comment]
@csarven are you satisfied with the conclusion?
